-- This file should undo anything in `up.sql`
ALTER TABLE users ALTER COLUMN monday DROP NOT NULL;
ALTER TABLE users ALTER COLUMN tuesday DROP NOT NULL;
ALTER TABLE users ALTER COLUMN wednesday DROP NOT NULL;
ALTER TABLE users ALTER COLUMN thursday DROP NOT NULL;
ALTER TABLE users ALTER COLUMN friday DROP NOT NULL;
ALTER TABLE users ALTER COLUMN saturday DROP NOT NULL;
ALTER TABLE users ALTER COLUMN sunday DROP NOT NULL;