-- Your SQL goes here
ALTER TABLE users ALTER COLUMN monday SET NOT NULL;
ALTER TABLE users ALTER COLUMN tuesday SET NOT NULL;
ALTER TABLE users ALTER COLUMN wednesday SET NOT NULL;
ALTER TABLE users ALTER COLUMN thursday SET NOT NULL;
ALTER TABLE users ALTER COLUMN friday SET NOT NULL;
ALTER TABLE users ALTER COLUMN saturday SET NOT NULL;
ALTER TABLE users ALTER COLUMN sunday SET NOT NULL;